export const tasksData = [
  {
    id: 1,
    title: "Complete project proposal",
    description: "Finalize the Q2 project proposal with budget details",
    priority: "high",
    status: "todo",
    dueDate: "2025-06-10",
    assignee: "John Doe",
  },
  {
    id: 2,
    title: "Review code changes",
    description: "Review pull requests for the authentication module",
    priority: "medium",
    status: "inprogress",
    dueDate: "2025-06-08",
    assignee: "Jane Smith",
  },
  {
    id: 3,
    title: "Update documentation",
    description: "Update API documentation for the new endpoints",
    priority: "low",
    status: "completed",
    dueDate: "2025-06-05",
    assignee: "Mike Johnson",
  },
  {
    id: 4,
    title: "Design system implementation",
    description: "Implement the new design system components",
    priority: "high",
    status: "inprogress",
    dueDate: "2025-06-12",
    assignee: "Sarah Wilson",
  },
  {
    id: 5,
    title: "Bug fixes",
    description: "Fix critical bugs reported by QA team",
    priority: "high",
    status: "todo",
    dueDate: "2025-06-09",
    assignee: "Alex Brown",
  },
];
